version: "3"
services:
  translate:
    image: node:18-alpine
    working_dir: /home/translateService
    volumes:
      - ./:/home/translateService
    command: /home/translateService/start.sh
    network_mode: host
    restart: always
