services:
  translate:
    image: node:18-alpine
    working_dir: /home/translateService
    volumes:
      - ./:/home/translateService
    command: /home/translateService/start.sh
    ports:
      - "9877:9877"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
